### ISSUE TITLE
Throwing errors when mapping array

### ISSUE THREAD

**Issue by mattgallivan** [AvdLee/Moya-SwiftyJSONMapper#17]
I have an issue when mapping over an array using the function

```
public func map<T: ALSwiftyJSONAble>(to type:[T.Type]) throws -> [T] {
        let jsonObject = try mapJSON()
        
        let mappedArray = JSON(jsonObject)
        let mappedObjectsArray = mappedArray.arrayValue.flatMap { T(jsonData: $0) }
        
        return mappedObjectsArray
    }
```

The bit that maps each item of the array is not allowed to fail because of the use of `flatMap`. For example, if the array contains three items of data of which two are valid, no errors will be thrown and an array of size two will be returned.

In some cases, it would be more useful if an error were thrown if the array contains invalid JSON (ie. returned nil from the `init()` function).

Similar to the function

```
public func map<T: ALSwiftyJSONAble>(to type:T.Type) throws -> T {
        let jsonObject = try mapJSON()
        
        guard let mappedObject = T(jsonData: JSON(jsonObject)) else {
            throw MoyaError.jsonMapping(self)
        }
        
        return mappedObject
    }
```
where the guard clause throws a `MoyaError` if the mapping is nil.

I can perform the map myself but I would rather contain the abstraction at its current level.

**Comment by mattgallivan** [comment]
I think the `flatMap` could be replaced by a `map` that throws an error if the resulting array contains any nil value.

This doesn't break the function header because it's already declared to be `throws`.

**Comment by AvdLee** [comment]
Feel free to open a PR for this!

**Comment by mattgallivan** [comment]
Sorry I'm not working with Swift at the moment but if I come back to this I'll write up a pull request.

**Comment by AvdLee** [comment]
Cool, all good. Can you reopen it by the time? Thanks!
