### ISSUE TITLE
Why specify Moya version?

### ISSUE THREAD

**Issue by retsohuang** [AvdLee/Moya-SwiftyJSONMapper#2]
I installed this pod with 'Moya-SwiftyJSONMapper/RxSwift' and it automaticly downgrade following pods
- Installing Moya 6.1.3 (was 6.2.0)
- Installing NSObject+Rx 1.2.0 (was 1.2.1)
- Installing RxCocoa 2.1.0 (was 2.2.0)
- Installing RxSwift 2.0.0 (was 2.2.0)

**Comment by AvdLee** [comment]
Good point, I'll fix it this week

**Comment by AvdLee** [comment]
Fixed in [1.0.3](https://github.com/AvdLee/Moya-SwiftyJSONMapper/releases/tag/1.0.3)
