### ISSUE TITLE
Unable to find a specification for `Moya-SwiftyJSONMapper (~> 6.0)`

### ISSUE THREAD

**Issue by vassily-fr** [AvdLee/Moya-SwiftyJSONMapper#30]
Hi, I need this new version of Moya-swiftyJSONMapper to fit with last Alamofire (linked dependancy)
But I can't manage to have this latest version to install. At best I have the 5.0 that install.

here is my pod file on a sample project
```
target 'TestMoya' do
  use_frameworks!

  pod "Moya-SwiftyJSONMapper", '~> 6.0'

  target 'TestMoyaTests' do
    inherit! :search_paths
  end

  target 'TestMoyaUITests' do
  end

end
```

here is the response:
```
TestMoya % pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Moya-SwiftyJSONMapper":
  In Podfile:
    Moya-SwiftyJSONMapper (~> 6.0)

None of your spec sources contain a spec satisfying the dependency: `Moya-SwiftyJSONMapper (~> 6.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

So I tried to force the repo location with "source" since there is a pod spec in this git. but still no luck.
Thanks for your help

**Comment by Ox8BADFOOD** [comment]
same question

**Comment by AvdLee** [comment]
Hey, sorry for this! I'm not actively maintaining this repo anymore, but I'm happy to accept any pull requests solving this issue accordingly.

**Comment by sandeepbol** [comment]
The issue has been fixed. The spec wasn't pushed to Cocoapods. Now the latest release is 6.1.0 supporting Moya 15.

**Comment by sandeepbol** [comment]
Please try doing `pod update --repo-update`
