### ISSUE TITLE
nested JSON

### ISSUE THREAD

**Issue by AsimNet** [AvdLee/Moya-SwiftyJSONMapper#5]
Hi

how to do something similar to this: 
`name = jsonData["User_Info"]["UName"].stringValue
`

thanks

**Comment by AvdLee** [comment]
Exactly like that! What's isn't working?

**Comment by AsimNet** [comment]
it returns empty value, not nil!

**Comment by AvdLee** [comment]
you can use .string for that:

``` swift
name = jsonData["User_Info"]["UName"].string 
```

**Comment by AsimNet** [comment]
when I print 
`name = jsonData["User_Info"]` it works and gives me the following output:

> [
>   {
>     "Email" : "XXX@gmail.com",
>     "UName" : "XXX",
>     "Status" : "2",
>     "Uid" : "1"
>   }
> ]

is it array?

**Comment by AvdLee** [comment]
Correct, it is. You can walk through the array or just select the first:

``` swift
name = jsonData["User_Info"].array[0]["UName"].string
```

To walk through the array, checkout the SwiftyJSON page:
https://github.com/SwiftyJSON/SwiftyJSON

**Comment by pabloepi** [comment]
I Antonie, I'm trying to create GIF objects from the Giphy API and I'm currently dealing with this code:

```
switch result {
            case let .Success(response):
                do {                    
                    let gifObject = try response.mapObject(GIF)
                } catch {
                    print(error)
                }

            case let .Failure(error):
                print(error)
            }

```

My doubt is, how can I iterate over the array of dictionaries from the JSON response and make the mapObject method send the right JSON structure to the GIF object init method.

Thanks in advance!

**Comment by AvdLee** [comment]
What about:

``` swift
response.mapArray(GIF)
```
